name: Docker Image CI

on: 
  push:
    branches:
    - main

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Login to GitHub Packages Docker Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.REGISTRY_TOKEN }}

        # Should use docker/build-push-action@v2
        - name: Build the tagged Docker image
          run: | 
            docker build . --file Dockerfile --tag ghcr.io/jon-andre/github-packages:latest
        
        - name: Push the tagged Docker image
          run: |
            docker push ghcr.io/jon-andre/github-packages:latest